### ISSUE TITLE
ValueError: No URL given for the wsdl

### ISSUE THREAD

**Issue by regsw** [jonathanelscpt/ciscocucmapi#23]
When using the Quick Start code posted in the documentation, I get the following when trying to run it.

  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\zeep\client.py", line 64, in __init__
    raise ValueError("No URL given for the wsdl")
ValueError: No URL given for the wsdl

I am using PyCharm latest edition against CUCM 11.5. I don't see a way to specify a WSDL in the documentation.

**Comment by regsw** [comment]
I found your other script "basic_auth.py" and used that as an example to add in the WSDL.

**Comment by fatestapestry** [comment]
Hi,

I haven't been actively maintaining this for a while...  I did a few brief tests and it seems like zeep may have changed and broken my model definitions.  Your mileage may vary.  If the lib is fubar, please log a bug and I'll look at it when I can...
